#!/usr/bin/env python3

import io
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "RayQueryShaders.h")

DXC = os.environ.get("DXC", "dxc")

DXIL = [
    ("RayQueryCompute", "RayQuery.hlsl", "cs_6_5", "csMain"),
    ("RayQueryProceduralCompute", "RayQueryProcedural.hlsl", "cs_6_5", "csMain"),
    ("RayTracingPipelineLibrary", "RayTracingPipeline.hlsl", "lib_6_3", None),
]

SPIRV = [
    ("RayQueryComputeSpirv", "RayQuery.hlsl", "cs_6_5", "csMain"),
    ("RayQueryProceduralComputeSpirv", "RayQueryProcedural.hlsl", "cs_6_5", "csMain"),
    ("RayTracingPipelineLibrarySpirv", "RayTracingPipeline.hlsl", "lib_6_3", None),
]


def run(command):
    result = subprocess.run(command, cwd=HERE, capture_output=True)

    if result.returncode != 0:
        sys.stderr.write(result.stdout.decode(errors="replace"))
        sys.stderr.write(result.stderr.decode(errors="replace"))
        raise SystemExit(f"command failed: {' '.join(command)}")


def compile_dxil(source, target, entry):
    output = os.path.join(HERE, source + ".cso")
    entry_arguments = ["-E", entry] if entry is not None else []
    run([DXC, "-nologo", "-T", target, *entry_arguments, "-Fo", output, source])

    with open(output, "rb") as handle:
        data = handle.read()

    os.remove(output)

    return list(data)


def compile_spirv(source, target, entry):
    output = os.path.join(HERE, source + ".spv")
    entry_arguments = ["-E", entry] if entry is not None else []
    run(
        [
            DXC,
            "-nologo",
            "-T",
            target,
            *entry_arguments,
            "-spirv",
            "-fspv-target-env=vulkan1.2",
            "-Fo",
            output,
            source,
        ]
    )

    with open(output, "rb") as handle:
        data = handle.read()

    os.remove(output)

    return list(struct.unpack(f"<{len(data) // 4}I", data))


def emit_array(out, element_type, name, values, per_line, formatter):
    out.write(f"static constexpr {element_type} {name}[] =\n{{\n")

    for index in range(0, len(values), per_line):
        chunk = values[index : index + per_line]
        out.write("\t" + ", ".join(formatter(value) for value in chunk))
        out.write(",\n" if index + per_line < len(values) else "};\n")

    out.write("\n")


def main():
    out = io.StringIO()
    out.write("// Generated by Shaders/generate.py. Do not edit by hand.\n\n")
    out.write("#pragma once\n\n#include <cstdint>\n\n")

    for name, source, target, entry in DXIL:
        emit_array(
            out,
            "std::uint8_t",
            name,
            compile_dxil(source, target, entry),
            12,
            lambda v: f"0x{v:02x}",
        )

    for name, source, target, entry in SPIRV:
        emit_array(
            out,
            "std::uint32_t",
            name,
            compile_spirv(source, target, entry),
            6,
            lambda v: f"0x{v:08x}",
        )

    text = out.getvalue()

    with open(OUT, "w", newline="\n") as handle:
        handle.write(text)

    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
