#!/usr/bin/env python3

import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "Shaders.h")

GLSLC = os.environ.get("GLSLC", "glslc")
FXC = os.environ.get("FXC", "fxc")

SPIRV = [
    ("VulkanCompute", "Gradient.comp", "compute"),
    ("VulkanVertex", "Fullscreen.vert", "vert"),
    ("VulkanFragment", "Sample.frag", "frag"),
]

DXBC = [
    ("D3D11Compute", "Gradient.hlsl", "cs_5_0", "csMain"),
    ("D3D11Vertex", "Fullscreen.hlsl", "vs_5_0", "vsMain"),
    ("D3D11Fragment", "Sample.hlsl", "ps_5_0", "psMain"),
]


def run(command):
    result = subprocess.run(command, cwd=HERE, capture_output=True)

    if result.returncode != 0:
        sys.stderr.write(result.stdout.decode(errors="replace"))
        sys.stderr.write(result.stderr.decode(errors="replace"))
        raise SystemExit(f"command failed: {' '.join(command)}")


def compile_spirv(source, stage):
    output = os.path.join(HERE, source + ".spv")
    run([GLSLC, f"-fshader-stage={stage}", source, "-O", "-o", output])

    with open(output, "rb") as handle:
        data = handle.read()

    os.remove(output)
    words = [int.from_bytes(data[i : i + 4], "little") for i in range(0, len(data), 4)]

    return words


def compile_dxbc(source, target, entry):
    output = os.path.join(HERE, source + ".cso")
    run([FXC, "/nologo", "/T", target, "/E", entry, "/Fo", output, source])

    with open(output, "rb") as handle:
        data = handle.read()

    os.remove(output)

    return list(data)


def emit_array(out, element_type, name, values, per_line, formatter):
    out.write(f"\tinline constexpr {element_type} {name}[] =\n\t\t{{\n")

    for index in range(0, len(values), per_line):
        chunk = values[index : index + per_line]
        out.write("\t\t\t" + ", ".join(formatter(value) for value in chunk))
        out.write(",\n" if index + per_line < len(values) else "};\n")

    out.write("\n")


def main():
    out = io.StringIO()
    out.write("// Generated by shaders/generate.py. Do not edit by hand.\n\n")
    out.write("#pragma once\n\n#include <cstdint>\n\nnamespace shaders\n{\n")

    for name, source, target, entry in DXBC:
        emit_array(
            out,
            "std::uint8_t",
            name,
            compile_dxbc(source, target, entry),
            12,
            lambda v: f"0x{v:02x}",
        )

    for name, source, stage in SPIRV:
        emit_array(
            out,
            "std::uint32_t",
            name,
            compile_spirv(source, stage),
            6,
            lambda v: f"0x{v:08x}",
        )

    text = out.getvalue().rstrip("\n") + "\n} // namespace shaders\n"

    with open(OUT, "w", newline="\n") as handle:
        handle.write(text)

    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
